<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>1.7 Including factors in linear models | Statistical Modelling</title>
  <meta name="description" content="A conceptual, visual and practical introduction to statistical modelling" />
  <meta name="generator" content="bookdown 0.37 and GitBook 2.6.7" />

  <meta property="og:title" content="1.7 Including factors in linear models | Statistical Modelling" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="A conceptual, visual and practical introduction to statistical modelling" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="1.7 Including factors in linear models | Statistical Modelling" />
  
  <meta name="twitter:description" content="A conceptual, visual and practical introduction to statistical modelling" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="prediction-black-cherry-trees.html"/>
<link rel="next" href="transforming-the-response-variable-giving-in-the-church-of-england.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/rglWebGL-binding-1.2.8/rglWebGL.js"></script>
<link href="libs/rglwidgetClass-1.2.8/rgl.css" rel="stylesheet" />
<script src="libs/rglwidgetClass-1.2.8/rglClass.min.js"></script>
<script src="libs/CanvasMatrix4-1.2.8/CanvasMatrix.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A visual and conceptual introduction to statistical modelling</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface: what’s the problem?</a></li>
<li class="chapter" data-level="" data-path="getting-started-with-r.html"><a href="getting-started-with-r.html"><i class="fa fa-check"></i>Getting started with R</a></li>
<li class="chapter" data-level="1" data-path="linear-models.html"><a href="linear-models.html"><i class="fa fa-check"></i><b>1</b> Linear models</a>
<ul>
<li class="chapter" data-level="1.1" data-path="simple-regression-rodents-revisited.html"><a href="simple-regression-rodents-revisited.html"><i class="fa fa-check"></i><b>1.1</b> Simple regression: rodents revisited</a></li>
<li class="chapter" data-level="1.2" data-path="linear-models-with-multiple-covariates.html"><a href="linear-models-with-multiple-covariates.html"><i class="fa fa-check"></i><b>1.2</b> Linear models with multiple covariates</a></li>
<li class="chapter" data-level="1.3" data-path="model-checking.html"><a href="model-checking.html"><i class="fa fa-check"></i><b>1.3</b> Model checking</a></li>
<li class="chapter" data-level="1.4" data-path="inference-on-coefficients.html"><a href="inference-on-coefficients.html"><i class="fa fa-check"></i><b>1.4</b> Inference on coefficients</a></li>
<li class="chapter" data-level="1.5" data-path="comparing-models.html"><a href="comparing-models.html"><i class="fa fa-check"></i><b>1.5</b> Comparing models</a></li>
<li class="chapter" data-level="1.6" data-path="prediction-black-cherry-trees.html"><a href="prediction-black-cherry-trees.html"><i class="fa fa-check"></i><b>1.6</b> Prediction: Black Cherry trees</a></li>
<li class="chapter" data-level="1.7" data-path="including-factors-in-linear-models.html"><a href="including-factors-in-linear-models.html"><i class="fa fa-check"></i><b>1.7</b> Including factors in linear models</a>
<ul>
<li class="chapter" data-level="1.7.1" data-path="including-factors-in-linear-models.html"><a href="including-factors-in-linear-models.html#comparing-groups-analysis-of-variance"><i class="fa fa-check"></i><b>1.7.1</b> Comparing groups: analysis of variance</a></li>
<li class="chapter" data-level="1.7.2" data-path="including-factors-in-linear-models.html"><a href="including-factors-in-linear-models.html#comparing-regression-lines-analysis-of-covariance"><i class="fa fa-check"></i><b>1.7.2</b> Comparing regression lines: analysis of covariance</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="transforming-the-response-variable-giving-in-the-church-of-england.html"><a href="transforming-the-response-variable-giving-in-the-church-of-england.html"><i class="fa fa-check"></i><b>1.8</b> Transforming the response variable: Giving in the Church of England</a></li>
<li class="chapter" data-level="1.9" data-path="simple-seasonal-terms.html"><a href="simple-seasonal-terms.html"><i class="fa fa-check"></i><b>1.9</b> Simple seasonal terms</a></li>
<li class="chapter" data-level="1.10" data-path="general-thoughts-on-models.html"><a href="general-thoughts-on-models.html"><i class="fa fa-check"></i><b>1.10</b> General thoughts on models</a>
<ul>
<li class="chapter" data-level="1.10.1" data-path="general-thoughts-on-models.html"><a href="general-thoughts-on-models.html#what-are-models-for"><i class="fa fa-check"></i><b>1.10.1</b> What are models for?</a></li>
<li class="chapter" data-level="1.10.2" data-path="general-thoughts-on-models.html"><a href="general-thoughts-on-models.html#model-selection"><i class="fa fa-check"></i><b>1.10.2</b> Model selection</a></li>
</ul></li>
<li class="chapter" data-level="1.11" data-path="exercises.html"><a href="exercises.html"><i class="fa fa-check"></i><b>1.11</b> Exercises</a>
<ul>
<li class="chapter" data-level="1.11.1" data-path="exercises.html"><a href="exercises.html#giving-in-the-church-of-england"><i class="fa fa-check"></i><b>1.11.1</b> Giving in the Church of England</a></li>
<li class="chapter" data-level="1.11.2" data-path="exercises.html"><a href="exercises.html#black-cherry-trees"><i class="fa fa-check"></i><b>1.11.2</b> Black Cherry trees</a></li>
<li class="chapter" data-level="1.11.3" data-path="exercises.html"><a href="exercises.html#cats"><i class="fa fa-check"></i><b>1.11.3</b> Cats</a></li>
<li class="chapter" data-level="1.11.4" data-path="exercises.html"><a href="exercises.html#respiratory-distress-syndrome"><i class="fa fa-check"></i><b>1.11.4</b> Respiratory distress syndrome</a></li>
<li class="chapter" data-level="1.11.5" data-path="exercises.html"><a href="exercises.html#the-clyde-data"><i class="fa fa-check"></i><b>1.11.5</b> The Clyde data</a></li>
<li class="chapter" data-level="1.11.6" data-path="exercises.html"><a href="exercises.html#water-quality-in-loch-leven"><i class="fa fa-check"></i><b>1.11.6</b> Water quality in Loch Leven</a></li>
<li class="chapter" data-level="1.11.7" data-path="exercises.html"><a href="exercises.html#so_2-over-europe"><i class="fa fa-check"></i><b>1.11.7</b> SO<span class="math inline">\(_2\)</span> over Europe</a></li>
<li class="chapter" data-level="1.11.8" data-path="exercises.html"><a href="exercises.html#maximal-heart-rate-and-age"><i class="fa fa-check"></i><b>1.11.8</b> Maximal heart rate and age</a></li>
<li class="chapter" data-level="1.11.9" data-path="exercises.html"><a href="exercises.html#the-effects-of-conservation"><i class="fa fa-check"></i><b>1.11.9</b> The effects of conservation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Modelling</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="including-factors-in-linear-models" class="section level2 hasAnchor" number="1.7">
<h2><span class="header-section-number">1.7</span> Including factors in linear models<a href="including-factors-in-linear-models.html#including-factors-in-linear-models" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="comparing-groups-analysis-of-variance" class="section level3 hasAnchor" number="1.7.1">
<h3><span class="header-section-number">1.7.1</span> Comparing groups: analysis of variance<a href="including-factors-in-linear-models.html#comparing-groups-analysis-of-variance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Comparing groups with one or two factors.</p>
</div>
<div id="comparing-regression-lines-analysis-of-covariance" class="section level3 hasAnchor" number="1.7.2">
<h3><span class="header-section-number">1.7.2</span> Comparing regression lines: analysis of covariance<a href="including-factors-in-linear-models.html#comparing-regression-lines-analysis-of-covariance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The terminology blocks is used to describe a factor which influences the response variable, but is not a primary interest in the experiment. This can also happen with continuous measurements. Two examples in this section illustrate how the inclusion of an appropriate covariate in an analysis can help to deliver an appropriate comparison of treatment groups, and prevent inappropriate conclusions being drawn.</p>
<blockquote>
<hr />
<p><strong>Example: Rainbow trout</strong><br />
When the behaviour of a group of trout is studied, some fish are observed to become dominant and others to become subordinate. Dominant fish have freedom of movement while subordinate fish tend to congregate in the periphery of the waterway and to avoid crossing the path of the dominant fish. Data on energy expenditure and ration of food were collected as part of a laboratory experiment. The data are available in the file <code>data/trout.dat</code>. Both energy expenditure and food ration are measured in units of
kilocalories per trout per day.</p>
<p>A detailed description of the experiment and an analysis of a more extensive set of data are provided by Metcalfe (1986), <em>Intraspecific variation in competitive ability and food intake in salmonids: consequences for energy budgets and growth rates</em>, Journal of Fish Biology 28, 525–31.</p>
<p>Is there evidence of a difference in food ration between dominant and subordinate fish?</p>
<hr />
</blockquote>
<p>The left hand panel below uses boxplots to give a direct comparison between the rations gained by the two groups of fish. This does suggest there may be a difference in mean values. The middle panel shows a plot of ration against expenditure, with a separate regression line for each group. Now the two groups are almost completely separated. The final plot fits a model which assumes the slopes of the two lines are identical.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="including-factors-in-linear-models.html#cb29-1" tabindex="-1"></a>  path  <span class="ot">&lt;-</span> <span class="fu">rp.datalink</span>(<span class="st">&quot;trout&quot;</span>)</span>
<span id="cb29-2"><a href="including-factors-in-linear-models.html#cb29-2" tabindex="-1"></a>  trout <span class="ot">&lt;-</span> <span class="fu">read.table</span>(path, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb29-3"><a href="including-factors-in-linear-models.html#cb29-3" tabindex="-1"></a>  <span class="fu">library</span>(ggplot2)</span>
<span id="cb29-4"><a href="including-factors-in-linear-models.html#cb29-4" tabindex="-1"></a></span>
<span id="cb29-5"><a href="including-factors-in-linear-models.html#cb29-5" tabindex="-1"></a>  model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ration <span class="sc">~</span> group, <span class="at">data =</span> trout)</span>
<span id="cb29-6"><a href="including-factors-in-linear-models.html#cb29-6" tabindex="-1"></a>  model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ration <span class="sc">~</span> group <span class="sc">*</span> energy, <span class="at">data =</span> trout)</span>
<span id="cb29-7"><a href="including-factors-in-linear-models.html#cb29-7" tabindex="-1"></a>  model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(ration <span class="sc">~</span> group <span class="sc">+</span> energy, <span class="at">data =</span> trout)</span>
<span id="cb29-8"><a href="including-factors-in-linear-models.html#cb29-8" tabindex="-1"></a></span>
<span id="cb29-9"><a href="including-factors-in-linear-models.html#cb29-9" tabindex="-1"></a>  <span class="fu">ggplot</span>(trout, <span class="fu">aes</span>(group, ration)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span>
<span id="cb29-10"><a href="including-factors-in-linear-models.html#cb29-10" tabindex="-1"></a>  <span class="fu">ggplot</span>(trout, <span class="fu">aes</span>(energy, ration, <span class="at">col =</span> group)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb29-11"><a href="including-factors-in-linear-models.html#cb29-11" tabindex="-1"></a>      <span class="fu">geom_line</span>(<span class="fu">aes</span>(energy, <span class="fu">fitted</span>(model2)), <span class="at">linewidth =</span> <span class="dv">2</span>)</span>
<span id="cb29-12"><a href="including-factors-in-linear-models.html#cb29-12" tabindex="-1"></a>  <span class="fu">ggplot</span>(trout, <span class="fu">aes</span>(energy, ration, <span class="at">col =</span> group)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb29-13"><a href="including-factors-in-linear-models.html#cb29-13" tabindex="-1"></a>      <span class="fu">geom_line</span>(<span class="fu">aes</span>(energy, <span class="fu">fitted</span>(model3)), <span class="at">linewidth =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-63-1.png" width="32%" /><img src="book_files/figure-html/unnamed-chunk-63-2.png" width="32%" /><img src="book_files/figure-html/unnamed-chunk-63-3.png" width="32%" /></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="including-factors-in-linear-models.html#cb30-1" tabindex="-1"></a>  <span class="fu">summary</span>(model1)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##                  Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)        79.644   4.422643 18.008235 5.843017e-13
## groupsubordinate  -16.815   6.254562 -2.688438 1.501569e-02</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="including-factors-in-linear-models.html#cb32-1" tabindex="-1"></a>  <span class="fu">summary</span>(model2)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##                           Estimate Std. Error    t value     Pr(&gt;|t|)
## (Intercept)             28.7070826   9.806857  2.9272461 9.866556e-03
## groupsubordinate         3.5475060  12.515835  0.2834414 7.804732e-01
## energy                   0.9150618   0.170874  5.3551863 6.440794e-05
## groupsubordinate:energy -0.3659327   0.216484 -1.6903454 1.103471e-01</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="including-factors-in-linear-models.html#cb34-1" tabindex="-1"></a>  <span class="fu">summary</span>(model3)<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##                     Estimate Std. Error   t value     Pr(&gt;|t|)
## (Intercept)       41.3977252  6.6451243  6.229789 9.149947e-06
## groupsubordinate -16.8239320  3.5566779 -4.730238 1.933996e-04
## energy             0.6870794  0.1104972  6.218068 9.360456e-06</code></pre>
<p>In the model summaries above, the simple comparison of groups shows a significant difference, with an estimated difference of 16.82. The model with separate regression lines shows that the interaction (allowing a different slope for each line) is not significant (see the term labelled <code>groupsubordinate:energy</code>). That suggests that we should consider the model with parallel regression lines. This also estimates the difference between the two groups, after adjusting for energy, to be 16.82.</p>
<p>So what advantage has there been here in fitting energy as a covariate? The answer lies in the precision of the estimates. For the simple comparison of groups the standard error is 6.25 while in the parallel regression lines model it is 3.56. So we are able to estimate the difference between the groups with greatly increased precision.</p>
<p>It would be easy to imagine cases where the simple group comparison was not significant but became so after including a suitable covariate.</p>
<blockquote>
<hr />
<p><strong>Example: Respiratory distress syndrome</strong><br />
Premature babies often suffer from a variety of problems, of which a major one is respiratory distress syndrome (RDS). It is thought that the occurrence of this syndrome might be related to a property of the blood called red cell deformability. This refers to the ability of red cells to change shape to pass through small pores. The rate (<code>lrate</code>, on a log scale) of blood flow through a set of three micrometre pores was recorded for two groups (<code>group</code>) of babies, some of whom suffered from respiratory distress syndrome and some who did not. The gestational age (<code>GA</code>) in weeks of each baby was also recorded.</p>
<p>Is there evidence of a difference in <code>lrate</code> between the two groups?</p>
<p>These data were kindly provided by Dr. Haider, Queen Mother’s Hospital, Glasgow. The data are available through <code>rp.datalink('rds')</code>.</p>
<hr />
</blockquote>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="including-factors-in-linear-models.html#cb36-1" tabindex="-1"></a>  path <span class="ot">&lt;-</span> <span class="fu">rp.datalink</span>(<span class="st">&#39;rds&#39;</span>)</span>
<span id="cb36-2"><a href="including-factors-in-linear-models.html#cb36-2" tabindex="-1"></a>  rds  <span class="ot">&lt;-</span> <span class="fu">read.table</span>(path, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb36-3"><a href="including-factors-in-linear-models.html#cb36-3" tabindex="-1"></a>  <span class="fu">library</span>(ggplot2)</span>
<span id="cb36-4"><a href="including-factors-in-linear-models.html#cb36-4" tabindex="-1"></a></span>
<span id="cb36-5"><a href="including-factors-in-linear-models.html#cb36-5" tabindex="-1"></a>  model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lrate <span class="sc">~</span> RDS, <span class="at">data =</span> rds)</span>
<span id="cb36-6"><a href="including-factors-in-linear-models.html#cb36-6" tabindex="-1"></a>  model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lrate <span class="sc">~</span> RDS <span class="sc">*</span> GA, <span class="at">data =</span> rds)</span>
<span id="cb36-7"><a href="including-factors-in-linear-models.html#cb36-7" tabindex="-1"></a>  model3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(lrate <span class="sc">~</span> RDS <span class="sc">+</span> GA, <span class="at">data =</span> rds)</span>
<span id="cb36-8"><a href="including-factors-in-linear-models.html#cb36-8" tabindex="-1"></a></span>
<span id="cb36-9"><a href="including-factors-in-linear-models.html#cb36-9" tabindex="-1"></a>  <span class="fu">ggplot</span>(rds, <span class="fu">aes</span>(RDS, lrate)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span>
<span id="cb36-10"><a href="including-factors-in-linear-models.html#cb36-10" tabindex="-1"></a>  <span class="fu">ggplot</span>(rds, <span class="fu">aes</span>(GA, lrate, <span class="at">col =</span> RDS)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb36-11"><a href="including-factors-in-linear-models.html#cb36-11" tabindex="-1"></a>      <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">fitted</span>(model2)), <span class="at">linewidth =</span> <span class="dv">2</span>)</span>
<span id="cb36-12"><a href="including-factors-in-linear-models.html#cb36-12" tabindex="-1"></a>  <span class="fu">ggplot</span>(rds, <span class="fu">aes</span>(GA, lrate, <span class="at">col =</span> RDS)) <span class="sc">+</span> <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb36-13"><a href="including-factors-in-linear-models.html#cb36-13" tabindex="-1"></a>      <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">fitted</span>(model3)), <span class="at">linewidth =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="book_files/figure-html/unnamed-chunk-65-1.png" width="32%" /><img src="book_files/figure-html/unnamed-chunk-65-2.png" width="32%" /><img src="book_files/figure-html/unnamed-chunk-65-3.png" width="32%" /></p>
<p>The three plots above again compare the groups directly, then adjust for the effects of gestational age with separate regression lines, and then lines with common slope. There are strikingly different results. Look at summaries of the three models to see that the direct group comparison (<code>model1</code>) shows a (just) significant result, while <code>model2</code> shows no evidence of interaction between group and gestational age and <code>model3</code> shows no evidence of a difference between the groups. So this is a case where the inclusion of a covariate prevents us from drawing an inappropriate conclusion of a group difference when in fact this is due the dominance of later gestational ages in the babies who do not have RDS.</p>
<p><span style="color: red;">&gt; <em>Another example - with several covariates?</em></span></p>
<p><span style="color: red;">&gt; <em>Trigonometric regression?</em></span></p>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="prediction-black-cherry-trees.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="transforming-the-response-variable-giving-in-the-church-of-england.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["book.pdf", "book.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
